### ISSUE TITLE
Why do you need a special font?

### ISSUE THREAD

**Issue by Frederik-Baetens** [Peltoche/lsd#10]
I don't know why you need a special font?

Is it just because the default unicode icons for folders (📁) are too big?

I'm asking because the unicode characters are supported by default in my terminal, but not the special fonts.

I think the symbols you need can definitely be found in default unicode: 🗋 🗁🗎 🔗 

Of course you could still keep support for the people that wanted prettier fonts, but I think it would be nice if lsd worked out of the box with standard unicode.

If you think this is a good idea, I will try to make a patch that uses the unicode symbols if the custom font can't be found.

**Comment by Peltoche** [comment]
Hello @Frederik-Baetens ,

The main reason for the nerd-font requirement is the wide selection of dev specific icons like git, rss, etc. It is fairly heavy and I can understand that some people doesn't want to install it just for some pretty icons. 

That's why I think that's a great idea.

Do you know a way to determine if a custom font is available or not?

**Comment by Frederik-Baetens** [comment]
Do you have a list of icons that lsd uses so that i can see if i can find unicode characters that convey a similar meaning.

As for detecting the font, the easiest solution would probably be to just allow the user to pass --unicode to lsd (something that would be made more convenient by using an alias).

**Comment by Peltoche** [comment]
You can find the icon list into  [icon.rs](https://github.com/Peltoche/lsd/blob/55c61722f32954947440445d667e15d3ff63da7b/src/icon.rs) but if you don't have the icon pack you will not be able to print them...

The `--unicode` flag seems to be a good idea.

**Comment by Peltoche** [comment]
Today there is two default icons: the [default folder](https://github.com/Peltoche/lsd/blob/526f02069526b249b90c544f31b2be31307e0cd1/src/icon.rs#L246) (`nf-fa-folder_open_o`) and the [default file](https://github.com/Peltoche/lsd/blob/526f02069526b249b90c544f31b2be31307e0cd1/src/icon.rs#L248) (`nf-fa-file`). They are used each time a custom icon is not found.

I think you can start by implementing just these two icons. After it will be easy to create a map between extensions and custom icons. 

I think that in order to make this feature easier,  a refactoring of the `icon` package is required. The package should be moved from the global Hashmaps and global functions to a struct, like the color package.  I start working on it.

**Comment by Peltoche** [comment]
With #39 this should be easier.

**Comment by Peltoche** [comment]
#40 created
