### ISSUE TITLE
LSD doesn't list files/archives/directories with root property

### ISSUE THREAD

**Issue by TitanHero** [Peltoche/lsd#127]
# The pwd path where I'm standing, is optional the issue happens with any path, even using sudo with lsd doesn't print anything.
![lsd](https://user-images.githubusercontent.com/18335094/52864017-dbdc8700-30fe-11e9-878c-9d03662fa00c.png)

## Expected behavior

lex@sys:/usr/share/terminator$ dir -la
total 36
drwxr-xr-x   3 root root  4096 oct 22 06:33 .
drwxr-xr-x 297 root root 12288 ene 20 11:48 ..
-rwxr-xr-x   1 root root  3695 jun 29  2017 remotinator
-rwxr-xr-x   1 root root  5242 jun 29  2017 terminator
-rw-r--r--   1 root root   281 jun 29  2017 terminator-1.91.egg-info
drwxr-xr-x   5 root root  4096 oct 22 06:34 terminatorlib

lsd doesn't print the list of files with root property
## Actual behavior 
lex@sys:/usr/share
/terminator$ lsd -la
lex@sys:/usr/share/terminator$

**Comment by Peltoche** [comment]
Hi @TitanHero ,

Do you have installed `lsd` with snap and without the `--classic` flag?

 If this is the case please reinstall it with the flag, it should solve you issue. The reason is that snap run `lsd` inside a jail where it can't access the filesystem. The `--classic` flag allows `lsd` to access all your filesystem.

If this is not the case... WTF!!?

**Comment by TitanHero** [comment]
### Thanks a lot

Cool, now that I think about it, I'm pretty sure that the problem is like you said, is due that I installed the snap version without the argument *--classic* , so, very thanks by give me some of your time, I wish you a lot of success and regards...
