### ISSUE TITLE
There is bug with icons on Xubuntu 18.04.2 & Tilix terminal

### ISSUE THREAD

**Issue by denisgolius** [Peltoche/lsd#137]
![screenshot_2019-03-04_14-11-25](https://user-images.githubusercontent.com/5650611/53732732-81298600-3e87-11e9-8bab-6e5716c49c29.png)

![screenshot_2019-03-04_14-13-28](https://user-images.githubusercontent.com/5650611/53732815-b3d37e80-3e87-11e9-9a91-60a64c0dd005.png)

```
dengolius@aspire:/tmp$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

```
dengolius@aspire:/tmp$ uname -a
Linux aspire 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Peltoche** [comment]
Hi @denisgolius ,

I think you don't have the correct font or you terminal is not configured to use it. You can find some instruction [here](https://github.com/Peltoche/lsd#prerequisites).

I think the documentation above should solve your issue so I close it but if the bug is something else or if you have any question don't hesitate to reopen it.
