### ISSUE TITLE
Add the `-A` flag for compatibility purpose

### ISSUE THREAD

**Issue by Peltoche** [Peltoche/lsd#147]
(From #136 )

As of right now -a is actually doing the job of -A. Maybe we should just have -A as a alias for -a for now until we get a fix for #122

**Comment by MADLAB96** [comment]
Hi! I was looking into implementing this and I had a couple of thoughts. Adding a clap [alias](https://docs.rs/clap/2.32.0/clap/struct.Arg.html#method.alias) does work, but it would be --A instead of -A. I'm going to look into adding [subcommand](https://docs.rs/clap/2.32.0/clap/struct.SubCommand.html) which might allow having -a and -A for the same command. This is only the second time I've looked at Clap though so I might be missing something regarding aliases. 

Since this seems to be just a temporary patch it might be worth considering --A being acceptable.

**Comment by Peltoche** [comment]
Hi @MADLAB96,

I don't think the `--A` solution would work because the main reason for this feature is to avoid breaking changes for the already existing aliases and you solution doesn't seems to solve that.
