### ISSUE TITLE
Icons are missing

### ISSUE THREAD

**Issue by leon1995** [Peltoche/lsd#169]
## Expected behavior
`lsd` show directories and stuff with icons

## Actual behavior
lists the stuff but icons are missing

`lsd`
![grafik](https://user-images.githubusercontent.com/15685899/54921348-db0cf100-4f05-11e9-97e0-04d8c42222b8.png)

Installed with homebrew on macos 10.14.3. Using [iterm2](https://iterm2.com/) and [fish](https://fishshell.com/)

**Comment by Peltoche** [comment]
Hi @leon1995,

I think you don't use a valid font. Please check the readme for the installation instructions and check that you terminal is configured with the correct font.

**Comment by Peltoche** [comment]
No news, so I guess it's solved. I needed don't hesitate to reopen the issue

**Comment by cmosetick** [comment]
@Peltoche I'm seeing the same exact issue as @leon1995. There are no icons. We can't be the only ones seeing this.
I'm also on Mac OS 10.14 with iterm2.

Your suggestion of prerequisite instructions is not sufficient. It would be extremely beneficial to provide specific instructions on your own project page to get the icons functional in iterm2 on Mac OS.

Despite the vast amount of information in the README file that you have pointed people to,(https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md)

I'm still not seeing a clear way to just get this working in a simple manner.

Here is some more info for you:

```
brew list | grep lsd
lsd

brew cask list | grep font
font-awesome-terminal-fonts
font-hack-nerd-font


lsd ~/Library/Fonts
  Droid+Sans+Mono+Awesome.ttf                Hack Bold Nerd Font Complete.ttf      Hack Regular Nerd Font Complete.ttf    SourceCodePro+Powerline+Awesome+Regular.ttf
  Hack Bold Italic Nerd Font Complete.ttf    Hack Italic Nerd Font Complete.ttf    Inconsolata+Awesome.ttf

lsd ~/Library/FontCollections
  Fixed Width.collection    Fun.collection    Modern.collection    PDF.collection    Traditional.collection    Web.collection
```

**Comment by Peltoche** [comment]
Hi @cmosetick ,

Some questions which I hope will help you solve your issue:

- Are you sure that you have correctly setup your terminal in order to use the font? 
- Have you tested with other fonts? I guess their is some subsets of nerd-font without all the icons. I know for sure that the `FuraCode Nerd Font Mono` works well (on linux with xterm at least)

As I don't have a Mac I can't dig into the issue so please, if you found something give us a hint.

**Comment by furey** [comment]
Hi @cmosetick,

Here's the steps I took to get icons working in iTerm2 on macOS:

https://github.com/Peltoche/lsd/issues/199#issuecomment-494218334

Cheers!

**Comment by Pigankle** [comment]
2024.  I had the same symptoms.  I didn't think it was a font issue because I was using a "Nerd Font". (Meslo LG). Turns out that not all nerd fonts are created equal.  I installed Fira, (and set terminal.app to use it, of course) and all the icons appeared as expected.  I slightly prefer the character shapes in Meslo, but not as much as I like having the little icons.  Another font that works, but which I don't like as much as Fira is AnonymicePro.  

BTW - I was using an old version of Meslo that I did _not_ get from NerdFonts.com.  It may be that the font package there has been updated to include the little icons....I may check that next.

**Comment by r0bbick** [comment]
I ran into this with iTerm on macOS 15.2 and went through all methods mentioned.

Turned out it was an iTerm2 issue. There is a "Nerd Font Bundle" that needs to be installed.

iTerm2: 
Settings... -> Profiles -> Text -> "Use a different font for non-ASCII text" -> Manage Special Exceptions -> "Install Nerd Font Bundle"
