### ISSUE TITLE
print sizes in bytes

### ISSUE THREAD

**Issue by maximevince** [Peltoche/lsd#211]
by default ls -l prints sizes in bytes,
lsd prints size in human-readable formats.. Sometimes I want to to know the exact byte size.
How to make lsd print sizes in byte?

**Comment by Peltoche** [comment]
Hi!

At the moment this is not possible and I don't aim to implement it for now. This format seems to be used by very few people and some other tools make it better than ls, the `du` command for example.

If many people needs it, we can add a new flag to specify the size format but at the moment I would like to keep as few formats as possible in order to keep the tool simple. 

I some people want this feature please add a :+1: to the comment above.

**Comment by maximevince** [comment]
Thanks for the quick reply! This is clear for me.

**Comment by meain** [comment]
Should be fixed with #235
