### ISSUE TITLE
Add indentation before filenames

### ISSUE THREAD

**Issue by alichtman** [Peltoche/lsd#22]
`lsd` looks like this:

<img width="187" alt="image" src="https://user-images.githubusercontent.com/20600565/49546960-69b71d00-f8d9-11e8-93af-10ea084426ce.png">

`colorls` looks like this:

<img width="216" alt="image" src="https://user-images.githubusercontent.com/20600565/49547019-85babe80-f8d9-11e8-90c6-8f89baa8e49c.png">

It would be cool to be able to set the indentation somehow.

**Comment by alichtman** [comment]
As a sidenote, this is a ton faster than `colorls`. As soon as some more features are added, I'm going to make this my default `ls` command.

**Comment by Peltoche** [comment]
Hello @alichtman,

Lsd is a little more than a simple rewrite as it aims to offer more features. That's why we can have some differences with the original colorls package.  For the tabulation there is several opinions on this subject:
- exa doesn't indent
- colorls indent 
- ls doesn't indent
- lsd doesn't indent

I think that it's a good idea to follow the classic ls as much as possible so I don't think lsd should implement this tabulation by default.

**Comment by alichtman** [comment]
> It would be cool to be able to set the indentation somehow.

I was thinking this could be an extra argument. I would use it, but I agree that it shouldn't be enabled by default.

**Comment by Peltoche** [comment]
The argument can be possible indeed. We only define the behavior in case of piped output (`lsd --indent | wc -c` for example). It seems many implementations disable this kind of feature in case of pipe in order to allow the following program to work properly. 

I think the following would do the trick:
```
lsd --prefix-indent=never # never indent (by default)
lsd --prefix-indent=auto # only indent when the output is a tty
lsd --prefix-indent=always # always indent
```

What do you think of it?

**Comment by alichtman** [comment]
This seems to make sense, yeah. I think this is a good solution, but there may be a better one. I'll think about it some more and let you know if I come up with anything.

**Comment by Peltoche** [comment]
As there is no news I close this ticket. Feel free to reopen it if you want to propose your solution
