### ISSUE TITLE
Performance of --tree vs default GNU `tree`

### ISSUE THREAD

**Issue by sluongng** [Peltoche/lsd#259]
## Expected behavior
Performance of `lsd --tree` should be on-par with GNU `tree` at the minimum

## Actual behavior
Benchmarking on my laptop over a large GOPATH(golang source tree) directory

```bash
~/work/golang> hyperfine --warmup 10 'lsd --tree ${GOPATH}' 'tree ${GOPATH}'
Benchmark #1: lsd --tree ${GOPATH}
  Time (mean ± σ):     329.3 ms ±  21.3 ms    [User: 207.4 ms, System: 118.6 ms]
  Range (min … max):   301.0 ms … 360.4 ms    10 runs

Benchmark #2: tree ${GOPATH}
  Time (mean ± σ):      78.2 ms ±  10.7 ms    [User: 37.0 ms, System: 40.8 ms]
  Range (min … max):    63.0 ms … 117.4 ms    47 runs

Summary
  'tree ${GOPATH}' ran
    4.21 ± 0.64 times faster than 'lsd --tree ${GOPATH}'
```

Laptop spec: 
CPU: i7-8550 @ 1.80 GHz x 8
Ram: 16Gb
OS: Ubuntu 19.04
Disk: Samsung PM961 NVMe 256Gb

Gopath size : 
```bash
tree | wc -l
13590
```

**Comment by sluongng** [comment]
personally I dont think that this is a `bug` but more of an `enhancement` request

Also: I notice that GNU tree seems to be printing out result immediately while lsd seem to be accumulating the result in mem(?) before finally flushing out? I have yet to dig into the architecture of LSD to understand this behaviour

**Comment by sluongng** [comment]
Hmm could you care to elaborate on the design decision of `fn inner_display_tree(...) -> String {...}` for it being
1. Recursive
2. Building up a mutable `output` string to be printed all at once later

This combine with the standard implementation "print as it go" (seen here https://github.com/kddeisz/tree) is the main cause of the performance hit?

**Comment by Peltoche** [comment]
Hi @sluongng ,

This is not a surprise that the tree command is way quicker than lsd. The code have been splited in three consecutive parts:
- The fetching
- The sorting
- The display

(cf: https://github.com/Peltoche/lsd/blob/master/src/core.rs#L69)

This separations make the code fare easier to understand and I hope it make the life easier for the first contributors. One of the downside is that it forbid a lot of optimizations like stream. This is an design choice. 

At the beginning the project was a rewrite of a ruby project and performances was a key feature. Now, with all the new features, it's less true and we try to keep the code as simple as possible in order to make the new features easy to add. The current performances seems ok for an everyday use so we will not invest a lot of work on it. If you need to manage a lot of file you can use a specialized tool like `tree`.

That said, if you find a way to improve the performances without adding too much complexity we will gladly accept a PR.
