### ISSUE TITLE
Display order

### ISSUE THREAD

**Issue by alaymari** [Peltoche/lsd#29]
First of all, thanks for a very handy tool. 

I noticed that the sorted list is displayed sidewise by `lsd`, whereas `ls` displays it from top to bottom. It just makes it difficult to find a file as we would be looking at the list in a different direction. Can the display be made similar to that of `ls`?

Are there any plans to implement all switches of `ls`?

**Comment by Peltoche** [comment]
Hello @alaymari,

It seems that all the projects have different opinions on this subject:
- colorls go sidewise
- exa go from top to bottom
- ls go from to to bottom

I decided to go sidewise because it seems more natural for me as I read from left to right but if everybody is used to the classic ls command it could be a good idea to go from top to bottom.

In any case it would be great to make it configurable with some options like `--vertical` and `--horizontal` or something in this taste.

**Comment by alaymari** [comment]
Agree with you. As the author, you make the choice :-) We are accustomed to the `ls` output which goes from top to bottom. If that can be changed via a switch, that would be nice.

As a user of the binary, want to know if the icon association can be changed. Presently symlinks are indistinguishable from regular files.

**Comment by alaymari** [comment]
Thanks for the change proposal. 

Regarding the icon for symlink, I think a color change like `ls` or `exa` does would be simpler.

**Comment by alaymari** [comment]
Just downloaded 0.8 version. Happy to see that the display default is top to bottom :-) Thanks.

I noticed an oddity (compared to `ls`): the directories/files are sorted so that uppercase names come first. Can that be made to follow `ls`'s behaviour of case insensitivity?

**Comment by Peltoche** [comment]
Good catch! #50 created.

Thanks for the report.
