### ISSUE TITLE
Color the name with a red background if a setuid flag is set

### ISSUE THREAD

**Issue by Peltoche** [Peltoche/lsd#44]
How to test:
```sh
mkdir /tmp/test

mkdir /tmp/test/dir
touch /tmp/test/file
chmod u+s /tmp/test/dir /tmp/test/file

lsd /tmp/test # `file` and `dir` should be printed with a red background

**Comment by loewenheim** [comment]
My idea would be to add a boolean parameter to the colorize function to control whether the background is highlighted or not. Is this acceptable, in your opinion?

**Comment by Peltoche** [comment]
I'm not a big fan of this kind of argument... What do you think of creating an `Elem::SetuidFile` and a `FileType::SetuidFile`  like the `Filetype::ExecutableFile` and `Elem::ExecutableFile`.  This will allows us to create a custom colors with a background.

**Comment by loewenheim** [comment]
That actually makes much more sense. I initially misunderstood how the `Elem` enum works.

**Comment by loewenheim** [comment]
Another way to do it would be to make the `File` variants of the `Elem` and `FileType` enums parametric:
```
enum Elem {
[…]
File(bool, bool),
[…]
}
```
By adding `SetuidFile` variants, we can replicate the behaviour of gnu ls, i.e. background red if suid, otherwise foreground green if executable, otherwise foreground white. But we cannot do a combination of foreground and background color because the file can only be a `SetuidFile` or an `ExecutableFile`.

**Comment by Peltoche** [comment]
Seems a great idea indeed.
