### ISSUE TITLE
Make the order by name case insensitive

### ISSUE THREAD

**Issue by Peltoche** [Peltoche/lsd#50]
Current outpout: 
```sh
 tmp  test  %  ⎈ prodild  prod  lsd -l
.rw-r--r--  peltoche  users  0 B  Mon Dec 10 10:16:50 2018    AAAAA
.rw-r--r--  peltoche  users  0 B  Mon Dec 10 10:16:57 2018    BBBB
.rw-r--r--  peltoche  users  0 B  Mon Dec 10 10:16:53 2018    aaaaa
.rw-r--r--  peltoche  users  0 B  Mon Dec 10 10:16:59 2018    bbbbb
```

expected output: 
```sh

 tmp  test  %  ⎈ prodild  prod  \ls -l
total 0
-rw-r--r-- 1 peltoche users 0 Dec 10 10:16 aaaaa
-rw-r--r-- 1 peltoche users 0 Dec 10 10:16 AAAAA
-rw-r--r-- 1 peltoche users 0 Dec 10 10:16 BBBB
-rw-r--r-- 1 peltoche users 0 Dec 10 10:16 bbbbb

```

**Comment by alaymari** [comment]
Downloaded the latest version 0.10. The issue still persists. The listing is still case sensitive. 

        % lsd                                                                                
        AAA  BBB  aaa  bbb                                                        
        % \ls                                                                                
        aaa  AAA  bbb  BBB                                                                    
        % exa                                                                                
        aaa  AAA  BBB  bbb

**Comment by Peltoche** [comment]
Fix merged -> #82 , thanks for the report

**Comment by liar666** [comment]
Hi,

Contrarily to @Peltoche , I want my `ls` command to differentiate between Lower and Upper case letters.
This is because:
- All (real) OSes (notably Unices) are case sensitive
- [because] All (real) programming languages are case sensitive, 
- [because] Most languages (at least latin ones I know of) are case sensitive (try to write the first/last name of someone in all-lower case in Italy/France/Portugal/UK and you'll be stoned!)
- That's also the reason why ASCII differentiates "a" and "A" as 2 different chars
- That's also why the original `ls` differentiates between the two (apart if you have asked it to localize the output by changing `LANG=C` in your environment).
 
So all (real/reasonable) computer scientists would want the output of any command to differentiate between Lower/Upper case letters.

So I don't see any reasonable reason to want to treat an Upper/Lower case letters in the exact same manner... But let's says a few people on earth want that.

In this case, that should be an option (not activated by default).

Would be great if you could provide some means to come back to the previous & correct behaviour (distinguishing L/U case letters), either by a CLI switch or by taking into account the LANG varenv (like original `ls`) or anything else.

Thanks :)

**Comment by zwpaper** [comment]
hi @liar666, thanks for the report, please open a new issue for the discussion, you could add a link to this one for reference.

BTW, adding the GNU ls behavior would be great as LSD is trying to align features with GNU ls.
