### ISSUE TITLE
Update the Snap

### ISSUE THREAD

**Issue by iMonZ** [Peltoche/lsd#537]
Hey,

I have found a snap of this tool: https://snapcraft.io/lsd
But its haven been updated for years now.
Could you please update this and add the Snapcraft version to the official installation methods?
(and add the arm64 architecture)
I could do that either, but I don't have the permissions for the snap.

**Comment by meain** [comment]
The snap package is something which we could not figure out how to get it working properly. We have stopped updating snap package. The only reason why that is still there is because once published, a snap could not be removed. Checkout https://github.com/Peltoche/lsd/issues/79 for more details.
ref: https://forum.snapcraft.io/t/how-can-a-developer-remove-her-his-app-from-snap-store/512
