### ISSUE TITLE
lsd -l displays weird output

### ISSUE THREAD

**Issue by AlbertMakdissi** [Peltoche/lsd#620]
- os:  Windows 10
- `lsd --version`: 0.21.0
- `echo $TERM`: 
- `echo $LS_COLORS`: 

## Expected behavior
lsd -l should display file informations with icons etc.

## Actual behavior
lsd -l displays weird output
![grafik](https://user-images.githubusercontent.com/96504290/152647952-72e3f75a-3559-4d96-940d-1097b06688df.png)

**Comment by meain** [comment]
This looks like it is because the terminal emulator does not seem to support colors properly. You can verify this by checking if `lsd --color never` shows proper output, just without the colors.

Unfortunately I will not be able to dig any more deeper into this as this looks like Git bash on Windows and I don't have a Windows setup.

**Comment by AlbertMakdissi** [comment]
yeah it displays proper, but without colors like you said. I also get an "os error 5" before it outputs.

**Comment by meain** [comment]
Could you post the full error or a screenshot.

Also, could you try with an older release and see if the color is working, say [0.20.1](https://github.com/Peltoche/lsd/releases/tag/0.20.1). Just wanted to check on a hunch.

**Comment by AlbertMakdissi** [comment]
![grafik](https://user-images.githubusercontent.com/96504290/152776640-a109dcea-b49e-4768-be63-31bd67bc7c6f.png)
But it goes a bit further. Also how would I install the 0.20.1 version? Something like scoop install lsd 0.20.1 doesnt work. Thx in advance

**Comment by meain** [comment]
With the screenshot, what I meant was the one with colors disabled. Just to understand the `os error 5` one.

About installing an older version, I believe you should be able to download a prebuilt binary from the release page for Window 64bit from [here](https://github.com/Peltoche/lsd/releases/download/0.20.1/lsd-0.20.1-x86_64-pc-windows-gnu.zip) or [here](https://github.com/Peltoche/lsd/releases/download/0.20.1/lsd-0.20.1-x86_64-pc-windows-msvc.zip) and run it.

**Comment by zwpaper** [comment]
there may be some issues related to the Windows Git Bash, please check https://stackoverflow.com/questions/27580668/how-to-correctly-enable-ansi-colors-in-conemu-git-bash/48206769#48206769

**Comment by AlbertMakdissi** [comment]
Regarding the screenshot with the colors disabled:
![grafik](https://user-images.githubusercontent.com/96504290/152992172-165b6be8-9831-449c-a4b0-d0b3df1d1cf8.png)
Note: Im not using git bash directly. Im using "windows terminal" app and added a git bash profile.

**Comment by meain** [comment]
> Note: Im not using git bash directly. Im using "windows terminal" app and added a git bash profile.

From my very limited understanding of how Windows terminal works, I believe that would not make any difference in the colors.

@zwpaper The reason why I thought of trying the older version of `lsd` was because, by default `ansi-term` uses just 8 colors but `crossterm` assumes that the terminal has 256 color support. So there is a chance that the old version might work and the current one might not.

**Comment by raulcanales** [comment]
I am experiencing the same "weird output" by running Git Bash for Windows, and can confirm that switching to LSD 0.20.1 fixes the problem

**Comment by meain** [comment]
@AlbertMakdissi Make sure you are running the binary you just extracted and not the globally installed version.
@raulcanales Thanks, that helps. I am assuming running `lsd -l` will give you similar output (with the weird stuff).

The issue here from what I understand is that in the older version, the folder colors were just using 16 colors if 256 was not necessary, but in the latest version it defaults to 256 color everywhere and Git bash cannot handle/parse 256 color escape codes.

**Comment by AlbertMakdissi** [comment]
How would I exactly run the binary instead of the globally installed version?

**Comment by meain** [comment]
Use the full path instead of the extracted binary inside the folder instead of running just `lsd`.

**Comment by AlbertMakdissi** [comment]
The full path is the installation path of the lsd.exe?

**Comment by meain** [comment]
If  you just extracted it from the in the current dir, that would be something like `./lsd-0.21.0-x86_64-pc-windows-gnu/lsd.exe`

**Comment by AlbertMakdissi** [comment]
I thought its closed but, apparently this does only work for the powershell.
![grafik](https://user-images.githubusercontent.com/96504290/153600620-28c010b8-aa3d-415a-81cf-3aa9066f3636.png)
![grafik](https://user-images.githubusercontent.com/96504290/153600702-8e0679e8-7b81-4462-b5ee-4735e93d3267.png)
 But for gitbash I still get this output:

**Comment by meain** [comment]
Unfortunately, I don't think we will be able to easily support git bash as we need 256 colors and git bash only support 16.
