### ISSUE TITLE
Exa feature parity

### ISSUE THREAD

**Issue by Mte90** [Peltoche/lsd#681]
This is the most famous ls alternative but is not so much developed compared to this one, https://github.com/ogham/exa

Anyway it is not clear if the features are the same, https://github.com/Peltoche/lsd/issues/218 as example for gitignore is missing.

**Comment by meain** [comment]
Not to nitpick, but `exa` is more popular than `lsd` if you go purely by Github stars, hehe 😂. 

With that out of the way, while both `exa` and `lsd` are both `ls` alternatives both have taken different approaches in how it does things in a lot of cases. Both have grown organically over time adding more features on top of `ls` in different directions even though we share a lot of common features. That said, there are a lot of features that we have not implemented just because no one got to it. You are always welcome to open issues or even better submit pull requests to improve `lsd`. :D

As for difference in features, you can go through the features of `lsd` in the man page or [here](https://github.com/Peltoche/lsd/blob/master/doc/lsd.md). I'm sure `exa` has something similar as well.
