### ISSUE TITLE
about performance

### ISSUE THREAD

**Issue by gliox** [Peltoche/lsd#811]
Hello.
- os: Garuda Linux x86_64
- `lsd --version`: lsd 0.23.1 (binary)
- `echo $TERM`: xterm-256color (xfce4-terminal 1.0.4)

Just a curiosity: when I run the first time the command `lsd -ALFil --timesort --date=relative` after a reboot or new start of the laptop, it takes, e.g., 5s528ms for output. The second run is fast. Why?

Edit: a silly question: where can I find the same LS_COLORS of the image at https://raw.githubusercontent.com/Peltoche/lsd/assets/screen_lsd.png?

**Comment by gliox** [comment]
Sorry, I don't know why, my configuration file is the problem. I moved it for a test and now it works fast

**Comment by meain** [comment]
`total-size: true` is probably what is causing a slowdown. Having this enabled will make it so that we have to compute the entire directory structure to figure out the size. As for the colors in the screenshot, you can get them(mostly) with https://github.com/Peltoche/lsd/issues/365#issuecomment-733095300 .
